version: "3.9"

volumes: 
  mongo_vol:

services:
  mongo:
    image: mongo
    container_name: mongoDB
    restart: always
    ports:
      - 27017:27017
   
    volumes:
     - mongo_vol:/data/db
    environment:
      MONGODB_INIT_ROOT_USERNAME: mongouser
      MONGODB_INIT_ROOT_PASSWORD: mongopwd

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MOGODB_ADMINUSERNAME: mongouser  
      ME_CONFIG_MOGODB_ADMINPASSWORD: mongowd  
  