version: '3.9'

services:
  postgresql_database:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=teste
    ports:
     - "5432:5432"
    volumes:
     - database-data:/data/db

  pegadmin4:
    image: dpage/pgadmin4
    restart: always
    environment: 
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    ports:
      - '5050:80'
    volumes:
      - pgadmin:/root/.pgadmin
volumes:
  database-data:
  pgadmin:
  